// const fact2 = require('./factorial/fact2')
// const prime2= require('./prime/prime2')
// const isPowerOfTwo  = require('./powerofTwo/index')
// const recursion  = require('./recursion/index')
// const linear =require('./search/linear')
// const binarySearch2 = require('./search/binarySearch2')
const recursiveBinarySearch = require('./search/recursiveBinary')